BACKUP_FILE:
  description: "Filename to save the backups to"
  default: "backup.sql"
  displayName: "BackupFile"
  trigger: backup
PASSWORD:
  default: "password"
DATABASE:
  default: "kudo"
  description: "Database name to provision."
